# Generated by Django 5.2.7 on 2025-10-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationintake',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่ต้องกิน'),
        ),
    ]
