# Generated by Django 5.2.7 on 2025-10-25 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่ออาการ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='รายละเอียด / โน้ตเพิ่มเติม')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
