# Generated by Django 5.2.7 on 2025-10-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='symptom',
            old_name='created_at',
            new_name='time',
        ),
    ]
