# Generated by Django 5.2.7 on 2025-10-25 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_alter_symptom_options_rename_created_at_symptom_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='symptom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='symptom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก'),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่ต้องกิน'),
        ),
    ]
