# Generated by Django 5.2.7 on 2025-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_alter_symptom_options_symptom_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่เกิดอาการ'),
        ),
    ]
