# Generated by Django 5.2.7 on 2025-10-25 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_alter_symptom_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='วันที่เกิดอาการ'),
        ),
    ]
