--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-10-25 23:03:54

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 240 (class 1259 OID 27021)
-- Name: appointments_appointment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_appointment (
    id bigint NOT NULL,
    doctor_name character varying(150) NOT NULL,
    doctor_phone character varying(20) NOT NULL,
    doctor_email character varying(254) NOT NULL,
    date date NOT NULL,
    at_time time without time zone NOT NULL,
    details text,
    clinic_id bigint,
    patient_id bigint NOT NULL,
    address text,
    condition text,
    title text
);


ALTER TABLE public.appointments_appointment OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 27020)
-- Name: appointments_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 26999)
-- Name: appointments_clinic; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_clinic (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.appointments_clinic OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 26998)
-- Name: appointments_clinic_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_clinic ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_clinic_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 27011)
-- Name: appointments_profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.appointments_profile (
    id bigint NOT NULL,
    phone_number character varying(15) NOT NULL,
    address text NOT NULL,
    birth_date date,
    user_id integer NOT NULL
);


ALTER TABLE public.appointments_profile OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 27010)
-- Name: appointments_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.appointments_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 26892)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 26891)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 26900)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 26899)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 26886)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 26885)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 26906)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 26914)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 26913)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 26905)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 26920)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 26919)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 26978)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 26977)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 26878)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 26877)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 26870)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 26869)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 27057)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 27098)
-- Name: medications_drug; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medications_drug (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    generic_name character varying(100),
    strength character varying(50),
    form character varying(10) NOT NULL,
    description text,
    user_id integer
);


ALTER TABLE public.medications_drug OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 27097)
-- Name: medications_drug_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medications_drug ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medications_drug_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 27106)
-- Name: medications_medicationintake; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medications_medicationintake (
    id bigint NOT NULL,
    dose character varying(100) NOT NULL,
    frequency character varying(10) NOT NULL,
    instruction character varying(10) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    note text,
    active boolean NOT NULL,
    drug_id bigint NOT NULL,
    user_id integer NOT NULL,
    "time" time without time zone
);


ALTER TABLE public.medications_medicationintake OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 27105)
-- Name: medications_medicationintake_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medications_medicationintake ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medications_medicationintake_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 27126)
-- Name: symptoms_symptom; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.symptoms_symptom (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    note text,
    "time" time without time zone,
    user_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    date date NOT NULL
);


ALTER TABLE public.symptoms_symptom OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 27125)
-- Name: symptoms_symptom_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.symptoms_symptom ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.symptoms_symptom_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5076 (class 0 OID 27021)
-- Dependencies: 240
-- Data for Name: appointments_appointment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_appointment (id, doctor_name, doctor_phone, doctor_email, date, at_time, details, clinic_id, patient_id, address, condition, title) FROM stdin;
2	Somchai Chaiyakul	0812345678	somchai@example.com	2025-10-26	10:30:00	Follow-up visit	17	1	\N	\N	\N
3	Warin K.		warin.k@example.com	2025-11-01	09:00:00	ECG & review	21	1	\N	\N	\N
\.


--
-- TOC entry 5072 (class 0 OID 26999)
-- Dependencies: 236
-- Data for Name: appointments_clinic; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_clinic (id, name, code, description, is_active) FROM stdin;
17	General Medicine	general	ทั่วไป/อายุรกรรม	t
18	Outpatient Department	opd	ผู้ป่วยนอก (OPD)	t
19	Inpatient Department	ipd	ผู้ป่วยใน (IPD)	t
20	Emergency Department	ed	อุบัติเหตุและฉุกเฉิน	t
21	Cardiology	cardiology	โรคหัวใจ	t
22	Neurology	neurology	ประสาทวิทยา	t
23	Orthopedics	orthopedics	กระดูกและข้อ	t
24	Pediatrics	pediatrics	กุมารเวชกรรม	t
25	Obstetrics & Gynecology	obgyn	สูตินรีเวชกรรม	t
26	Surgery	surgery	ศัลยกรรม	t
27	Dermatology	dermatology	ผิวหนัง	t
28	ENT	ent	โสต ศอ นาสิก (หู คอ จมูก)	t
29	Ophthalmology	ophthalmology	จักษุ	t
30	Radiology	radiology	รังสีวิทยา	t
31	Rehabilitation	rehab	เวชศาสตร์ฟื้นฟู / กายภาพบำบัด	t
32	Nutrition	nutrition	โภชนาการ	t
\.


--
-- TOC entry 5074 (class 0 OID 27011)
-- Dependencies: 238
-- Data for Name: appointments_profile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.appointments_profile (id, phone_number, address, birth_date, user_id) FROM stdin;
1	0555555555		\N	2
2			\N	1
3			\N	3
\.


--
-- TOC entry 5060 (class 0 OID 26892)
-- Dependencies: 224
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 5062 (class 0 OID 26900)
-- Dependencies: 226
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5058 (class 0 OID 26886)
-- Dependencies: 222
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add clinic	7	add_clinic
26	Can change clinic	7	change_clinic
27	Can delete clinic	7	delete_clinic
28	Can view clinic	7	view_clinic
29	Can add profile	8	add_profile
30	Can change profile	8	change_profile
31	Can delete profile	8	delete_profile
32	Can view profile	8	view_profile
33	Can add appointment	9	add_appointment
34	Can change appointment	9	change_appointment
35	Can delete appointment	9	delete_appointment
36	Can view appointment	9	view_appointment
37	Can add medication intake	10	add_medicationintake
38	Can change medication intake	10	change_medicationintake
39	Can delete medication intake	10	delete_medicationintake
40	Can view medication intake	10	view_medicationintake
41	Can add drug	11	add_drug
42	Can change drug	11	change_drug
43	Can delete drug	11	delete_drug
44	Can view drug	11	view_drug
45	Can add symptom	12	add_symptom
46	Can change symptom	12	change_symptom
47	Can delete symptom	12	delete_symptom
48	Can view symptom	12	view_symptom
\.


--
-- TOC entry 5064 (class 0 OID 26906)
-- Dependencies: 228
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$ADEbpsvS4mo4xq0ZGsOehw$Xl6N7n11GHdpHsJOcOHs611xRJRLnJ6r1/1UoGYfRoc=	2025-10-25 15:03:45.950995+07	t	admin				t	t	2025-10-25 11:53:04.097481+07
2	pbkdf2_sha256$1000000$aCAa1t9zSap3jzR4NLXfXE$1ypvimchOma8UGoN5j2CnSUkhcQbXnKkh/Lp41+CuB4=	2025-10-25 22:20:13.59659+07	f	srisamorn	Srisamorn	Morning		f	t	2025-10-25 11:53:55+07
3	pbkdf2_sha256$1000000$7n52sTWwLmCxrCXYvzYPgv$laOeCM3eFGyMLDqECKBr6F+CjJtV1VgLw+4N+V3JM9A=	2025-10-25 22:20:36.720417+07	f	manop	Manop	Kittipitikhun	manop@test.com	f	t	2025-10-25 22:10:30.223923+07
\.


--
-- TOC entry 5066 (class 0 OID 26914)
-- Dependencies: 230
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 5068 (class 0 OID 26920)
-- Dependencies: 232
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 5070 (class 0 OID 26978)
-- Dependencies: 234
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-10-25 11:53:55.968492+07	2	srisamorn	1	[{"added": {}}]	4	1
2	2025-10-25 11:56:29.952647+07	2	srisamorn	2	[{"changed": {"fields": ["First name", "Last name"]}}]	4	1
\.


--
-- TOC entry 5056 (class 0 OID 26878)
-- Dependencies: 220
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	appointments	clinic
8	appointments	profile
9	appointments	appointment
10	medications	medicationintake
11	medications	drug
12	symptoms	symptom
\.


--
-- TOC entry 5054 (class 0 OID 26870)
-- Dependencies: 218
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-10-25 11:29:37.73496+07
2	auth	0001_initial	2025-10-25 11:29:37.893979+07
3	admin	0001_initial	2025-10-25 11:29:37.939544+07
4	admin	0002_logentry_remove_auto_add	2025-10-25 11:29:37.950049+07
5	admin	0003_logentry_add_action_flag_choices	2025-10-25 11:29:37.95964+07
6	appointments	0001_initial	2025-10-25 11:29:38.072347+07
7	contenttypes	0002_remove_content_type_name	2025-10-25 11:29:38.098873+07
8	auth	0002_alter_permission_name_max_length	2025-10-25 11:29:38.115414+07
9	auth	0003_alter_user_email_max_length	2025-10-25 11:29:38.126408+07
10	auth	0004_alter_user_username_opts	2025-10-25 11:29:38.135933+07
11	auth	0005_alter_user_last_login_null	2025-10-25 11:29:38.147941+07
12	auth	0006_require_contenttypes_0002	2025-10-25 11:29:38.148937+07
13	auth	0007_alter_validators_add_error_messages	2025-10-25 11:29:38.159998+07
14	auth	0008_alter_user_username_max_length	2025-10-25 11:29:38.179525+07
15	auth	0009_alter_user_last_name_max_length	2025-10-25 11:29:38.191538+07
16	auth	0010_alter_group_name_max_length	2025-10-25 11:29:38.206059+07
17	auth	0011_update_proxy_permissions	2025-10-25 11:29:38.22007+07
18	auth	0012_alter_user_first_name_max_length	2025-10-25 11:29:38.23059+07
19	sessions	0001_initial	2025-10-25 11:29:38.252111+07
21	medications	0001_initial	2025-10-25 17:56:53.837271+07
22	symptoms	0001_initial	2025-10-25 18:47:56.226102+07
23	medications	0002_medicationintake_time	2025-10-25 20:51:09.467794+07
24	appointments	0002_appointment_address_appointment_condition_and_more	2025-10-25 21:28:00.134928+07
25	symptoms	0002_alter_symptom_options_rename_created_at_symptom_time	2025-10-25 21:34:53.76787+07
26	symptoms	0003_alter_symptom_options_symptom_created_at_and_more	2025-10-25 21:41:44.577277+07
27	symptoms	0004_alter_symptom_time	2025-10-25 21:47:10.196718+07
28	symptoms	0005_symptom_date	2025-10-25 21:54:07.551198+07
29	medications	0003_drug_user	2025-10-25 22:19:13.810049+07
\.


--
-- TOC entry 5077 (class 0 OID 27057)
-- Dependencies: 241
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
hgjhyq12xkcfgi9onzdssss3f2htk0iu	.eJxVjMsOwiAQRf-FtSGdPoBx6d5vIAMzSNVAUtqV8d-1SRe6veec-1KetjX7rcniZ1ZnNajT7xYoPqTsgO9UblXHWtZlDnpX9EGbvlaW5-Vw_w4ytfytE5PrISREFJo6oRgSY-CBjYMJRmdJKHUkSYx1CJHNAKYniwAQ7KjeHxrfOJ0:1vCg4K:f1GnJwvr2KrTiNofwt5b1Q7fK3HDHzC9TvFiQgcGoT4	2025-11-08 22:20:36.724433+07
\.


--
-- TOC entry 5079 (class 0 OID 27098)
-- Dependencies: 243
-- Data for Name: medications_drug; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medications_drug (id, name, generic_name, strength, form, description, user_id) FROM stdin;
1	Paracetamol	Paracetamol	500 mg	TAB	ยาแก้ปวด ลดไข้ ใช้ได้ทั่วไป	2
3	ยาม้า	Horse	50000 mg	TAB	กินแล้วดีดเหมือนม้า	2
4	ยาบ้า	Drug	500 mg	TAB	ทำให้อยู่ในอาการหลอนประสาท	3
\.


--
-- TOC entry 5081 (class 0 OID 27106)
-- Dependencies: 245
-- Data for Name: medications_medicationintake; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.medications_medicationintake (id, dose, frequency, instruction, start_date, end_date, note, active, drug_id, user_id, "time") FROM stdin;
1	1 เม็ด	BID	AFTER	2025-10-25	\N	ทานหลังอาหารเช้า-เย็น	t	1	2	20:30:00
2	5 เม็ด	PRN	WITH	2025-10-25	2025-10-25		t	3	2	20:00:00
3	1 เม็ด	QD	NONE	2025-10-25	\N	ทาน เมื่อมีอาการลงแดง	t	4	3	22:30:00
\.


--
-- TOC entry 5083 (class 0 OID 27126)
-- Dependencies: 247
-- Data for Name: symptoms_symptom; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.symptoms_symptom (id, name, note, "time", user_id, created_at, date) FROM stdin;
2	ปวดอึ	อึไม่ออก	12:05:45.975634	2	2025-10-25 21:41:44.511178+07	2025-10-25
3	ลองเพิ่มอาการจากปุ่มเมนู	ทดสอบ	13:36:30.471217	2	2025-10-25 21:41:44.511178+07	2025-10-25
4	ปวดหัว	ปวดหัวข้างซ้าย	14:42:00	2	2025-10-25 21:49:23.202135+07	2025-10-25
5	ลองเพิ่มวันที่และเวลาย้อนหลัง	ทดสอบ	16:58:00	2	2025-10-25 21:59:29.038335+07	2025-10-14
6	จะเป็นลม	หน้าม้าตายาย	22:07:00	2	2025-10-25 22:07:49.696988+07	2025-10-25
7	ตัวเริ่มมีเกล็ด	เหมือนจะเป็นนางเงือก	22:07:00	2	2025-10-25 22:08:13.95342+07	2025-10-25
8	ไอ	คันคอ	22:11:00	3	2025-10-25 22:12:07.390317+07	2025-10-25
\.


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 239
-- Name: appointments_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_appointment_id_seq', 10, true);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 235
-- Name: appointments_clinic_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_clinic_id_seq', 32, true);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 237
-- Name: appointments_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.appointments_profile_id_seq', 3, true);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 223
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 225
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 221
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 227
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 233
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 2, true);


--
-- TOC entry 5099 (class 0 OID 0)
-- Dependencies: 219
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- TOC entry 5100 (class 0 OID 0)
-- Dependencies: 217
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 29, true);


--
-- TOC entry 5101 (class 0 OID 0)
-- Dependencies: 242
-- Name: medications_drug_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medications_drug_id_seq', 4, true);


--
-- TOC entry 5102 (class 0 OID 0)
-- Dependencies: 244
-- Name: medications_medicationintake_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.medications_medicationintake_id_seq', 3, true);


--
-- TOC entry 5103 (class 0 OID 0)
-- Dependencies: 246
-- Name: symptoms_symptom_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.symptoms_symptom_id_seq', 8, true);


--
-- TOC entry 4877 (class 2606 OID 27027)
-- Name: appointments_appointment appointments_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appointment_pkey PRIMARY KEY (id);


--
-- TOC entry 4862 (class 2606 OID 27009)
-- Name: appointments_clinic appointments_clinic_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_clinic
    ADD CONSTRAINT appointments_clinic_code_key UNIQUE (code);


--
-- TOC entry 4865 (class 2606 OID 27007)
-- Name: appointments_clinic appointments_clinic_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_clinic
    ADD CONSTRAINT appointments_clinic_name_key UNIQUE (name);


--
-- TOC entry 4867 (class 2606 OID 27005)
-- Name: appointments_clinic appointments_clinic_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_clinic
    ADD CONSTRAINT appointments_clinic_pkey PRIMARY KEY (id);


--
-- TOC entry 4869 (class 2606 OID 27017)
-- Name: appointments_profile appointments_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_profile
    ADD CONSTRAINT appointments_profile_pkey PRIMARY KEY (id);


--
-- TOC entry 4871 (class 2606 OID 27019)
-- Name: appointments_profile appointments_profile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_profile
    ADD CONSTRAINT appointments_profile_user_id_key UNIQUE (user_id);


--
-- TOC entry 4830 (class 2606 OID 27055)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 4835 (class 2606 OID 26935)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 4838 (class 2606 OID 26904)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4832 (class 2606 OID 26896)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 4825 (class 2606 OID 26926)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 4827 (class 2606 OID 26890)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 26918)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 4849 (class 2606 OID 26950)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 4840 (class 2606 OID 26910)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 26924)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 4855 (class 2606 OID 26964)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 4843 (class 2606 OID 27050)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 4858 (class 2606 OID 26985)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 4820 (class 2606 OID 26884)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 4822 (class 2606 OID 26882)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 4818 (class 2606 OID 26876)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 4880 (class 2606 OID 27063)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 4883 (class 2606 OID 27104)
-- Name: medications_drug medications_drug_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medications_drug
    ADD CONSTRAINT medications_drug_pkey PRIMARY KEY (id);


--
-- TOC entry 4887 (class 2606 OID 27112)
-- Name: medications_medicationintake medications_medicationintake_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medications_medicationintake
    ADD CONSTRAINT medications_medicationintake_pkey PRIMARY KEY (id);


--
-- TOC entry 4890 (class 2606 OID 27132)
-- Name: symptoms_symptom symptoms_symptom_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.symptoms_symptom
    ADD CONSTRAINT symptoms_symptom_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 1259 OID 27048)
-- Name: appointment_clinic__b05966_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointment_clinic__b05966_idx ON public.appointments_appointment USING btree (clinic_id);


--
-- TOC entry 4873 (class 1259 OID 27047)
-- Name: appointment_date_808441_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointment_date_808441_idx ON public.appointments_appointment USING btree (date, at_time);


--
-- TOC entry 4874 (class 1259 OID 27045)
-- Name: appointments_appointment_clinic_id_b4f8299f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_appointment_clinic_id_b4f8299f ON public.appointments_appointment USING btree (clinic_id);


--
-- TOC entry 4875 (class 1259 OID 27046)
-- Name: appointments_appointment_patient_id_631d13da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_appointment_patient_id_631d13da ON public.appointments_appointment USING btree (patient_id);


--
-- TOC entry 4860 (class 1259 OID 27029)
-- Name: appointments_clinic_code_b8ecd164_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_clinic_code_b8ecd164_like ON public.appointments_clinic USING btree (code varchar_pattern_ops);


--
-- TOC entry 4863 (class 1259 OID 27028)
-- Name: appointments_clinic_name_a941beed_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX appointments_clinic_name_a941beed_like ON public.appointments_clinic USING btree (name varchar_pattern_ops);


--
-- TOC entry 4828 (class 1259 OID 27056)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 4833 (class 1259 OID 26946)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 4836 (class 1259 OID 26947)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 4823 (class 1259 OID 26932)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 4844 (class 1259 OID 26962)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 4847 (class 1259 OID 26961)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 4850 (class 1259 OID 26976)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 4853 (class 1259 OID 26975)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 4841 (class 1259 OID 27051)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 4856 (class 1259 OID 26996)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 4859 (class 1259 OID 26997)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 4878 (class 1259 OID 27065)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 4881 (class 1259 OID 27064)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 4884 (class 1259 OID 27153)
-- Name: medications_drug_user_id_2cdffaff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX medications_drug_user_id_2cdffaff ON public.medications_drug USING btree (user_id);


--
-- TOC entry 4885 (class 1259 OID 27123)
-- Name: medications_medicationintake_drug_id_4842ee70; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX medications_medicationintake_drug_id_4842ee70 ON public.medications_medicationintake USING btree (drug_id);


--
-- TOC entry 4888 (class 1259 OID 27124)
-- Name: medications_medicationintake_user_id_3dc77711; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX medications_medicationintake_user_id_3dc77711 ON public.medications_medicationintake USING btree (user_id);


--
-- TOC entry 4891 (class 1259 OID 27138)
-- Name: symptoms_symptom_user_id_10b8f131; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX symptoms_symptom_user_id_10b8f131 ON public.symptoms_symptom USING btree (user_id);


--
-- TOC entry 4902 (class 2606 OID 27035)
-- Name: appointments_appointment appointments_appoint_clinic_id_b4f8299f_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_clinic_id_b4f8299f_fk_appointme FOREIGN KEY (clinic_id) REFERENCES public.appointments_clinic(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4903 (class 2606 OID 27040)
-- Name: appointments_appointment appointments_appoint_patient_id_631d13da_fk_appointme; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_appointment
    ADD CONSTRAINT appointments_appoint_patient_id_631d13da_fk_appointme FOREIGN KEY (patient_id) REFERENCES public.appointments_profile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4901 (class 2606 OID 27030)
-- Name: appointments_profile appointments_profile_user_id_19362faf_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.appointments_profile
    ADD CONSTRAINT appointments_profile_user_id_19362faf_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4893 (class 2606 OID 26941)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4894 (class 2606 OID 26936)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4892 (class 2606 OID 26927)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4895 (class 2606 OID 26956)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4896 (class 2606 OID 26951)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4897 (class 2606 OID 26970)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4898 (class 2606 OID 26965)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4899 (class 2606 OID 26986)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4900 (class 2606 OID 26991)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4904 (class 2606 OID 27148)
-- Name: medications_drug medications_drug_user_id_2cdffaff_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medications_drug
    ADD CONSTRAINT medications_drug_user_id_2cdffaff_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4905 (class 2606 OID 27113)
-- Name: medications_medicationintake medications_medicati_drug_id_4842ee70_fk_medicatio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medications_medicationintake
    ADD CONSTRAINT medications_medicati_drug_id_4842ee70_fk_medicatio FOREIGN KEY (drug_id) REFERENCES public.medications_drug(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4906 (class 2606 OID 27118)
-- Name: medications_medicationintake medications_medicationintake_user_id_3dc77711_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medications_medicationintake
    ADD CONSTRAINT medications_medicationintake_user_id_3dc77711_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 4907 (class 2606 OID 27133)
-- Name: symptoms_symptom symptoms_symptom_user_id_10b8f131_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.symptoms_symptom
    ADD CONSTRAINT symptoms_symptom_user_id_10b8f131_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2025-10-25 23:03:54

--
-- PostgreSQL database dump complete
--

