# Generated by Django 5.2.7 on 2025-10-25 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อยา')),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อสามัญ (Generic)')),
                ('strength', models.CharField(blank=True, max_length=50, null=True, verbose_name='ขนาดยา เช่น 500mg')),
                ('form', models.CharField(choices=[('TAB', 'เม็ด'), ('CAP', 'แคปซูล'), ('SYP', 'น้ำเชื่อม'), ('SOL', 'สารละลาย/หยด'), ('INJ', 'ฉีด'), ('OTH', 'อื่น ๆ')], default='TAB', max_length=10, verbose_name='รูปแบบยา')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose', models.CharField(help_text='เช่น 1 เม็ด', max_length=100, verbose_name='ขนาด/จำนวน')),
                ('frequency', models.CharField(choices=[('QD', 'วันละครั้ง'), ('BID', 'วันละ 2 ครั้ง (เช้า–เย็น)'), ('TID', 'วันละ 3 ครั้ง'), ('QID', 'วันละ 4 ครั้ง'), ('PRN', 'เมื่อมีอาการ')], default='QD', max_length=10, verbose_name='ความถี่')),
                ('instruction', models.CharField(choices=[('BEFORE', 'ก่อนอาหาร'), ('AFTER', 'หลังอาหาร'), ('WITH', 'พร้อมอาหาร'), ('NONE', 'ไม่ระบุ')], default='NONE', max_length=10, verbose_name='คำแนะนำ')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='วันที่เริ่ม')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุด')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('active', models.BooleanField(default=True, verbose_name='ยังใช้อยู่')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.drug', verbose_name='ยา')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'ordering': ['-active', 'start_date'],
            },
        ),
    ]
